### ISSUE TITLE
Install docs finished? Can't login to platform panel.  

### ISSUE THREAD

**Issue by Mr-Negative** [netgen/ezplatform-sylius#1]
Is it instalation doc finished?
Becouse https://github.com/ezsystems/ezplatform/blob/master/INSTALL.md
php -d memory_limit=-1 composer.phar create-project --no-dev ezsystems/ezplatform
suggest that it's only copied from ezsystems/ezplatform repository. Am i wrong?

I use it and I use build in server.
User admin password: publish from docs dosn't work in http://127.0.0.1:8001/ez

**Comment by ilukac** [comment]
This repo code is still under development, once we mark a tag it will be ready :)

Thanks for the interest

**Comment by emodric** [comment]
@Mr-Negative The idea has changed from before when we had eZ Publish Community integration. Now Sylius users are alpha & omega. You will use them to login to backend AND frontend, but before you can do that, you need to connect the eZ and Sylius users with the command available in the integration bundle: https://github.com/netgen/NetgenEzSyliusBundle/commit/56d355f036b5a388fee6481b23da526f1047d2da

As you noticed, docs are copied directly from eZ, but this will be updated as soon as we have something relativelly stable. As @ilukac mentioned, this repo is currently under development, but most important, Sylius is heavily under development in version `1.0@dev` and is higly volatile right now, meaning that stuff will most probably break day to day. We're hoping to have everything ready by the time Sylius reaches the beta version in November (http://sylius.org/blog/sylius-roadmap-update), which will mean that at least the API will be stable.

**Comment by Mr-Negative** [comment]
@emodric  Yeah it does make more sense to do this this way. Are you planning on integrating panels in any way? Becouse for me two panels aren't a problem, but for "end user" not from IT it would be very confusing.

**Comment by emodric** [comment]
> Are you planning on integrating panels in any way? Becouse for me two panels aren't a problem, but for "end user" not from IT it would be very confusing.

We do, but only in Netgen's own admin interface. There is no integration planned for now to eZ Platform UI or original legacy admin.

**Comment by Mr-Negative** [comment]
Are you planning to share it and make as part of this repository, or it will be only for use of your company?

**Comment by emodric** [comment]
> Are you planning to share it and make as part of this repository, or it will be only for use of your company?

It will not be open sourced, sadly, as it is a commercial product. You can contact @ilukac (on Twitter also @ilukac), if you wish to have a peek.

**Comment by Mr-Negative** [comment]
It's all good. :-) I'm more than capable to do my own integration, i'm just "lazy" and better ask than do "redundant" work. Thx

**Comment by emodric** [comment]
@Mr-Negative You might be interested in the fact that integration of admin interfaces of eZ Platform and Sylius is *now* open sourced :)

https://github.com/netgen/NetgenAdminUIBundle
https://github.com/netgen/NetgenAdminUISyliusBundle

**Comment by emodric** [comment]
@Mr-Negative Ofcourse, it's *now opensourced*, instead of *not opensourced* :)
