### ISSUE TITLE
I can't install it. Composer breaks my computer

### ISSUE THREAD

**Issue by silviuvoicu** [netgen/ezplatform-sylius#5]
Hi, I clone it, but when running composer install, it breaks my computer. It increase memory until it becomes unusable and I have to restart.
 I have the latest php 7.3.11 and composer 1.9.0 
Try composer with other projects and works just fine there.

**Comment by emodric** [comment]
Hi. Thank you for your report! However, I'm not sure how to help you. Composer can be quite a bit memory hog, especially when there are a lot of dependencies like here. Note that most of those are coming from eZ Platform.

Have you tried installing it on a different computer?

**Comment by silviuvoicu** [comment]
I only have one :( 
What are the minimum requirements for this project? 
It may be the case, that I need a better computer

**Comment by emodric** [comment]
There are no special requirements, but eZ Platform has been known to have issues with composer install with less than 8 GB RAM.
